import type { Language } from "../site-copy";

export const analysisCopy = {
  uk: {
    languageLabel: "Мова",
    back: "На головну",
    eyebrow: "Video Technique Audit · персонально від тренера",
    title: "Побачити головну помилку у техніці й знати, що робити далі.",
    intro:
      "Надішліть відео одного стилю. Протягом 48 годин ви отримаєте розбір з доказовими кадрами, трьома пріоритетами та вправами для наступних тренувань.",
    price: "₴2 490 / €59",
    priceNote: "Разова оплата · відповідь до 48 годин після отримання придатного відео",
    cta: "Підготувати заявку",
    proof: ["7 років тренерської практики", "5000+ годин персональної роботи", "Без підписки"],
    artifactLabel: "Що буде у розборі",
    artifactTitle: "Не просто коментар. Робочий план на наступний захід у воду.",
    deliverables: [
      ["01", "Evidence-кадри", "Стоп-кадри з розміткою моментів, які визначають ефективність руху."],
      ["02", "Три пріоритети", "Що змінювати спочатку, а що поки не чіпати, щоб не розпорошувати увагу."],
      ["03", "Практичні вправи", "Конкретні підказки й вправи, які можна одразу додати до тренування."],
      ["04", "20 хвилин із тренером", "Короткий дзвінок для уточнень після отримання розбору."],
    ],
    sampleLabel: "Формат доказів",
    sampleTitle: "Кадр → спостереження → наступна дія",
    sampleItems: ["Вхід руки", "Положення корпусу", "Опора у воді"],
    guideLabel: "Як зняти відео",
    guideTitle: "Достатньо смартфона і 10–15 хвилин у басейні.",
    guide: [
      "Зніміть 15–25 метрів збоку, тримаючи все тіло в кадрі.",
      "Додайте короткий ракурс спереду або ззаду, якщо це безпечно.",
      "Знімайте у звичному темпі. Не намагайтеся показати ідеальний заплив.",
    ],
    processLabel: "Як це працює",
    process: [
      ["01", "Короткий бриф", "Ви описуєте ціль, досвід і готуєте повідомлення."],
      ["02", "Відео в месенджері", "Надсилаєте матеріал напряму тренеру у Telegram або WhatsApp."],
      ["03", "Розбір за 48 годин", "Отримуєте структурований аналіз і домовляєтесь про короткий дзвінок."],
    ],
    formLabel: "Ваш контекст",
    formTitle: "Підготуйте заявку за дві хвилини.",
    fields: {
      name: "Ім’я",
      namePlaceholder: "Як до вас звертатися",
      goal: "Ціль",
      goalPlaceholder: "Наприклад: впевнено проплисти 1,9 км",
      level: "Рівень",
      stroke: "Стиль",
      selectPlaceholder: "Оберіть варіант",
      deadline: "Термін або дата старту",
      deadlinePlaceholder: "Наприклад: старт через 8 тижнів",
      videoReady: "Відео вже готове",
    },
    levels: ["Починаю плавати", "Плаваю для себе", "Триатлет-аматор", "Змагаюся у плаванні"],
    strokes: ["Кроль", "Брас", "На спині", "Батерфляй"],
    prepare: "Підготувати повідомлення",
    prepared: "Заявка готова",
    copy: "Скопіювати",
    copied: "Скопійовано",
    telegram: "Відкрити Telegram",
    whatsapp: "Надіслати у WhatsApp",
    handoff:
      "Форма нічого не надсилає і не зберігає. Ви самі копіюєте текст та обираєте месенджер.",
    consent:
      "Надсилаючи відео, ви підтверджуєте, що маєте право передати матеріал для приватного тренерського розбору.",
    disclaimer: "Професійна інтерпретація, не медичний діагноз і не гарантія результату.",
    upgradeLabel: "Якщо потрібна система",
    upgradeTitle: "Вартість розбору зарахую у перший місяць персонального ведення.",
    upgradeText:
      "Після аудиту ви вже будете знати стартову точку. Якщо вирішимо працювати далі, перетворимо пріоритети на тижневий план і цикл зворотного зв’язку.",
    upgradeCta: "Подивитися персональне ведення",
  },
  en: {
    languageLabel: "Language",
    back: "Back home",
    eyebrow: "Video Technique Audit · reviewed personally by the coach",
    title: "See the one technique issue that matters most and know what to do next.",
    intro:
      "Send a video of one stroke. Within 48 hours, receive an evidence-led review with annotated frames, three priorities and drills for your next sessions.",
    price: "€59 / ₴2,490",
    priceNote: "One-time payment · delivered within 48 hours of receiving usable footage",
    cta: "Prepare your request",
    proof: ["7 years of coaching practice", "5,000+ hours of personal work", "No subscription"],
    artifactLabel: "What you receive",
    artifactTitle: "More than comments. A working plan for your next pool session.",
    deliverables: [
      ["01", "Evidence frames", "Annotated stills showing the moments that shape your movement efficiency."],
      ["02", "Three priorities", "What to change first and what to leave alone so your attention stays focused."],
      ["03", "Practical drills", "Clear cues and exercises you can add to your next session."],
      ["04", "20 minutes with the coach", "A short follow-up call for questions after you receive the review."],
    ],
    sampleLabel: "Evidence format",
    sampleTitle: "Frame → observation → next action",
    sampleItems: ["Hand entry", "Body position", "Water catch"],
    guideLabel: "How to film",
    guideTitle: "A smartphone and 10–15 minutes at the pool are enough.",
    guide: [
      "Film 15–25 metres from the side, keeping your full body in frame.",
      "Add a short front or rear angle if it is safe to do so.",
      "Swim at your normal pace. Do not try to perform a perfect take.",
    ],
    processLabel: "How it works",
    process: [
      ["01", "Short brief", "Share your goal and experience, then prepare the message."],
      ["02", "Video in messenger", "Send the footage directly to the coach via Telegram or WhatsApp."],
      ["03", "Review in 48 hours", "Receive the structured analysis and arrange your short follow-up call."],
    ],
    formLabel: "Your context",
    formTitle: "Prepare your request in two minutes.",
    fields: {
      name: "Name",
      namePlaceholder: "How should I address you?",
      goal: "Goal",
      goalPlaceholder: "For example: swim 1.9 km with confidence",
      level: "Level",
      stroke: "Stroke",
      selectPlaceholder: "Choose an option",
      deadline: "Deadline or race date",
      deadlinePlaceholder: "For example: race in 8 weeks",
      videoReady: "My video is ready",
    },
    levels: ["Just getting started", "Recreational swimmer", "Amateur triathlete", "Competitive swimmer"],
    strokes: ["Freestyle", "Breaststroke", "Backstroke", "Butterfly"],
    prepare: "Prepare message",
    prepared: "Your request is ready",
    copy: "Copy message",
    copied: "Copied",
    telegram: "Open Telegram",
    whatsapp: "Send in WhatsApp",
    handoff:
      "This form sends and stores nothing. You copy the text yourself and choose your messenger.",
    consent:
      "By sending footage, you confirm that you have the right to share it for a private coaching review.",
    disclaimer: "Professional interpretation, not a medical diagnosis or a guaranteed outcome.",
    upgradeLabel: "When you need a system",
    upgradeTitle: "I will credit the audit price toward your first month of personal coaching.",
    upgradeText:
      "After the audit, you will know your starting point. If we decide to continue, we turn the priorities into a weekly plan and a feedback loop.",
    upgradeCta: "See personal coaching",
  },
} as const satisfies Record<Language, object>;
